services:    
  postgres:
    container_name: postgres
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--locale=en_US.UTF-8 --encoding=UTF8"
    restart: always 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5433:5432"
