services:
  odoo-proxy:
    image: nginx:latest
    container_name: odoo-proxy
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./config/odoo17-ce.conf:/etc/nginx/conf.d/odoo17-ce.conf
    restart: always # run as a service
    networks: 
      - odoo-network  
    tty: true
